# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dreamcity-dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.7.0'

      - name: npm install, build, and test dreamcity app
        working-directory: ./app
        env:
          CI: false
        run: |
          npm install
          npm run build --if-present

      - name: npm install, build, and webpack candy machine app
        working-directory: ./candy-machine
        env:
          CI: false
        run: |
          npm install
          npm run build --if-present
          npx webpack

      - name: Upload main app artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./app/build/

      - name: Upload candy-machine artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: candy-machine-app
          path: ./candy-machine/build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download main app artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Download candy-machine app artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: candy-machine-app

      - name: 'Deploy to Azure Main Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dreamcity-dev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B7F7DA3738CA436EB51A8DC8EB0EE7BD }}
          package: .

      - name: 'Deploy to Azure Candy Machine Wallet Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'candy-machine-dev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.PUBLISHPROFILE_CANDYMACHINE }}
          package: .

